# Build Docker image, push it to DockerHub, and run a project build.
# This will run every sunday at midnight.

name: Build ARCS

on:
  pull_request:
    branches:
    - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build_image:
    name: Build ARCS image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
          ref: docker-vnc

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARCS image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/arcs:latest
          push: true

  catkin_build:
    name: Build ARCS Project
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Run 'catkin build'
        run: make test
