name: Docker

on:
  pull_request:
    branches: [ master, devel ]

jobs:
  build_image:
    name: Build ARCS image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull latest Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/arcs:latest ||
             echo "No ARCS image to cache from"

      - name: Build ARCS image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          cache-from: ${{ secrets.DOCKER_USERNAME }}/arcs:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/arcs:latest
